using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace cptmApiTeste.Migrations
{
    /// <inheritdoc />
    public partial class AddUsuarioAuth : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'USUARIO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE ""USUARIO"" (
            ""ID"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
            ""USERNAME"" NVARCHAR2(2000) NOT NULL,
            ""PASSWORD"" NVARCHAR2(2000) NOT NULL,
            ""ROLE"" NVARCHAR2(2000) NOT NULL,
            CONSTRAINT ""PK_USUARIO"" PRIMARY KEY (""ID"")
        )';
    END IF;
END;");

            migrationBuilder.Sql(@"
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IX_USUARIO_USERNAME';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX ""IX_USUARIO_USERNAME"" ON ""USUARIO"" (""USERNAME"")';
    END IF;
END;");

            migrationBuilder.Sql(@"
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM ""USUARIO"" WHERE ""USERNAME"" = 'admin';
    IF v_count = 0 THEN
        INSERT INTO ""USUARIO"" (""USERNAME"", ""PASSWORD"", ""ROLE"") VALUES ('admin', 'admin', 'admin');
    END IF;

    SELECT COUNT(*) INTO v_count FROM ""USUARIO"" WHERE ""USERNAME"" = 'user';
    IF v_count = 0 THEN
        INSERT INTO ""USUARIO"" (""USERNAME"", ""PASSWORD"", ""ROLE"") VALUES ('user', 'user', 'user');
    END IF;
END;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'USUARIO';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE ""USUARIO"" CASCADE CONSTRAINTS';
    END IF;
END;");
        }
    }
}