services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: cptm-oracle-db
    restart: unless-stopped
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: root
      APP_USER: RHUAN
      APP_USER_PASSWORD: root
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: